create table public.weight_ticket_status_logs (
  event_key text not null default ('WTSTATUS-'::text || gen_random_uuid()::text),
  action text not null,
  weight_ticket_doc_no text not null,
  doc_type text not null,
  from_status text null,
  to_status text not null,
  gross_weight_snapshot numeric not null default 0,
  deduct_weight_snapshot numeric not null default 0,
  net_weight_snapshot numeric not null default 0,
  note text null,
  meta jsonb null,
  created_at timestamptz not null default now(),
  created_by text null,
  id bigint generated by default as identity primary key,
  weight_ticket_id bigint not null references public.weight_tickets(id) on delete restrict
);

create unique index idx_weight_ticket_status_logs_event_key
  on public.weight_ticket_status_logs(event_key);

create index idx_weight_ticket_status_logs_ticket_created
  on public.weight_ticket_status_logs(weight_ticket_id, created_at desc);

create index idx_weight_ticket_status_logs_doc_no
  on public.weight_ticket_status_logs(weight_ticket_doc_no);

with base_tickets as (
  select
    wt.id,
    wt.doc_no,
    wt.doc_type,
    coalesce(wt.gross_weight, 0) as gross_weight,
    coalesce(wt.deduct_weight, 0) as deduct_weight,
    coalesce(wt.net_weight, 0) as net_weight,
    wt.status as current_status,
    case
      when wt.doc_type = 'WTI' then 'received'
      when wt.doc_type = 'WTO' then 'delivered'
      else coalesce(wt.status, 'received')
    end as initial_status,
    wt.cancel_note,
    wt.cancelled_at,
    wt.created_at,
    wt.created_by,
    wt.updated_at,
    wt.updated_by,
    wt.cancelled_by
  from public.weight_tickets wt
)
insert into public.weight_ticket_status_logs (
  event_key,
  action,
  weight_ticket_doc_no,
  doc_type,
  from_status,
  to_status,
  gross_weight_snapshot,
  deduct_weight_snapshot,
  net_weight_snapshot,
  meta,
  created_at,
  created_by,
  weight_ticket_id
)
select
  'WTSTATUS-' || doc_no || '-0001' as event_key,
  'created' as action,
  doc_no,
  doc_type,
  null as from_status,
  initial_status as to_status,
  gross_weight,
  deduct_weight,
  net_weight,
  jsonb_build_object('source', 'migration_backfill') as meta,
  coalesce(created_at, now()) as created_at,
  created_by,
  id
from base_tickets;

with base_tickets as (
  select
    wt.id,
    wt.doc_no,
    wt.doc_type,
    coalesce(wt.gross_weight, 0) as gross_weight,
    coalesce(wt.deduct_weight, 0) as deduct_weight,
    coalesce(wt.net_weight, 0) as net_weight,
    wt.status as current_status,
    case
      when wt.doc_type = 'WTI' then 'received'
      when wt.doc_type = 'WTO' then 'delivered'
      else coalesce(wt.status, 'received')
    end as initial_status,
    wt.cancel_note,
    wt.cancelled_at,
    wt.created_at,
    wt.created_by,
    wt.updated_at,
    wt.updated_by,
    wt.cancelled_by
  from public.weight_tickets wt
)
insert into public.weight_ticket_status_logs (
  event_key,
  action,
  weight_ticket_doc_no,
  doc_type,
  from_status,
  to_status,
  gross_weight_snapshot,
  deduct_weight_snapshot,
  net_weight_snapshot,
  note,
  meta,
  created_at,
  created_by,
  weight_ticket_id
)
select
  'WTSTATUS-' || doc_no || '-0002' as event_key,
  case when current_status = 'cancelled' then 'cancelled' else 'status_synced' end as action,
  doc_no,
  doc_type,
  initial_status as from_status,
  current_status as to_status,
  gross_weight,
  deduct_weight,
  net_weight,
  cancel_note as note,
  jsonb_build_object('source', 'migration_backfill', 'reason', 'current_status_snapshot') as meta,
  case
    when current_status = 'cancelled' then coalesce(cancelled_at, updated_at, created_at, now())
    else coalesce(updated_at, created_at, now())
  end as created_at,
  case
    when current_status = 'cancelled' then coalesce(cancelled_by, updated_by, created_by)
    else coalesce(updated_by, created_by)
  end as created_by,
  id
from base_tickets
where current_status is distinct from initial_status;
