create table if not exists public.sales_bill_lines (
  id bigint generated by default as identity primary key,
  sales_bill_id bigint not null references public.sales_bills(id) on delete restrict,
  line_no integer not null,
  product_id bigint null references public.products(id) on delete restrict,
  product_code_snapshot text not null,
  product_name_snapshot text not null,
  unit_snapshot text null,
  gross_weight numeric not null default 0,
  deduct_weight numeric not null default 0,
  net_weight numeric not null default 0,
  qty numeric not null default 0,
  unit_price numeric not null default 0,
  discount_amount numeric not null default 0,
  line_amount numeric not null default 0,
  vat_amount numeric not null default 0,
  status text not null default 'active',
  notes text null,
  meta jsonb null,
  created_at timestamptz not null default now(),
  created_by text null,
  updated_at timestamptz not null default now(),
  updated_by text null,
  version integer not null default 1,
  constraint sales_bill_lines_status_check check (status in ('active', 'cancelled', 'reversed')),
  constraint sales_bill_lines_non_negative_check check (
    gross_weight >= 0
    and deduct_weight >= 0
    and net_weight >= 0
    and qty >= 0
    and unit_price >= 0
    and discount_amount >= 0
    and line_amount >= 0
    and vat_amount >= 0
  )
);

create unique index if not exists uq_sales_bill_lines_bill_line
  on public.sales_bill_lines(sales_bill_id, line_no);

create index if not exists idx_sales_bill_lines_bill_status
  on public.sales_bill_lines(sales_bill_id, status);

create index if not exists idx_sales_bill_lines_product_status
  on public.sales_bill_lines(product_id, status)
  where product_id is not null;

create table if not exists public.sales_bill_source_allocations (
  id bigint generated by default as identity primary key,
  sales_bill_id bigint not null references public.sales_bills(id) on delete restrict,
  sales_bill_line_id bigint null references public.sales_bill_lines(id) on delete restrict,
  sales_line_no integer not null,
  source_type text not null,
  source_doc_no text not null,
  source_line_no integer null,
  source_id bigint null,
  weight_ticket_id bigint null references public.weight_tickets(id) on delete restrict,
  stock_issue_id bigint null references public.stock_issues(id) on delete restrict,
  product_id bigint null references public.products(id) on delete restrict,
  product_code_snapshot text not null,
  product_name_snapshot text not null,
  allocated_qty numeric not null default 0,
  allocated_gross_weight numeric not null default 0,
  allocated_deduct_weight numeric not null default 0,
  allocated_net_weight numeric not null default 0,
  movement_owner text not null,
  stock_ledger_ref_type text null,
  status text not null default 'active',
  notes text null,
  meta jsonb null,
  created_at timestamptz not null default now(),
  created_by text null,
  updated_at timestamptz not null default now(),
  updated_by text null,
  version integer not null default 1,
  constraint sales_bill_source_allocations_source_type_check check (source_type in ('WTO', 'PSALE', 'DIRECT_STOCK')),
  constraint sales_bill_source_allocations_movement_owner_check check (movement_owner in ('SALES_BILL', 'PSALE')),
  constraint sales_bill_source_allocations_status_check check (status in ('active', 'cancelled', 'reversed')),
  constraint sales_bill_source_allocations_qty_check check (
    allocated_qty >= 0
    and allocated_gross_weight >= 0
    and allocated_deduct_weight >= 0
    and allocated_net_weight >= 0
  )
);

create index if not exists idx_sales_bill_source_allocations_bill_line_status
  on public.sales_bill_source_allocations(sales_bill_id, sales_line_no, status);

create index if not exists idx_sales_bill_source_allocations_source_status
  on public.sales_bill_source_allocations(source_type, source_doc_no, status);

create index if not exists idx_sales_bill_source_allocations_wto
  on public.sales_bill_source_allocations(weight_ticket_id, status)
  where weight_ticket_id is not null;

create index if not exists idx_sales_bill_source_allocations_psale
  on public.sales_bill_source_allocations(stock_issue_id, status)
  where stock_issue_id is not null;

create table if not exists public.sales_bill_po_sell_allocations (
  id bigint generated by default as identity primary key,
  sales_bill_id bigint not null references public.sales_bills(id) on delete restrict,
  sales_bill_line_id bigint null references public.sales_bill_lines(id) on delete restrict,
  sales_line_no integer not null,
  allocation_type text not null,
  po_sell_id bigint null references public.po_sells(id) on delete restrict,
  po_sell_doc_no text null,
  po_sell_line_no integer null,
  product_id bigint null references public.products(id) on delete restrict,
  product_code_snapshot text not null,
  product_name_snapshot text not null,
  allocated_qty numeric not null default 0,
  unit_price numeric not null default 0,
  allocated_amount numeric not null default 0,
  status text not null default 'active',
  notes text null,
  meta jsonb null,
  created_at timestamptz not null default now(),
  created_by text null,
  updated_at timestamptz not null default now(),
  updated_by text null,
  version integer not null default 1,
  constraint sales_bill_po_sell_allocations_type_check check (allocation_type in ('PO_SELL', 'SPOT_SALE')),
  constraint sales_bill_po_sell_allocations_status_check check (status in ('active', 'cancelled', 'reversed')),
  constraint sales_bill_po_sell_allocations_qty_check check (
    allocated_qty >= 0
    and unit_price >= 0
    and allocated_amount >= 0
  ),
  constraint sales_bill_po_sell_allocations_po_required_check check (
    (allocation_type = 'PO_SELL' and po_sell_id is not null and po_sell_doc_no is not null)
    or (allocation_type = 'SPOT_SALE')
  )
);

create index if not exists idx_sales_bill_po_sell_allocations_bill_line_status
  on public.sales_bill_po_sell_allocations(sales_bill_id, sales_line_no, status);

create index if not exists idx_sales_bill_po_sell_allocations_po_status
  on public.sales_bill_po_sell_allocations(po_sell_id, status)
  where po_sell_id is not null;

create index if not exists idx_sales_bill_po_sell_allocations_type_status
  on public.sales_bill_po_sell_allocations(allocation_type, status);

create table if not exists public.sales_bill_customer_advance_allocations (
  id bigint generated by default as identity primary key,
  sales_bill_id bigint not null references public.sales_bills(id) on delete restrict,
  customer_advance_doc_no text not null,
  customer_id bigint null references public.customers(id) on delete restrict,
  customer_code_snapshot text not null,
  customer_name_snapshot text not null,
  allocated_amount numeric not null default 0,
  outstanding_before numeric not null default 0,
  outstanding_after numeric not null default 0,
  status text not null default 'active',
  notes text null,
  meta jsonb null,
  created_at timestamptz not null default now(),
  created_by text null,
  updated_at timestamptz not null default now(),
  updated_by text null,
  version integer not null default 1,
  constraint sales_bill_customer_advance_allocations_status_check check (status in ('active', 'cancelled', 'reversed')),
  constraint sales_bill_customer_advance_allocations_amount_check check (
    allocated_amount >= 0
    and outstanding_before >= 0
    and outstanding_after >= 0
  )
);

create index if not exists idx_sales_bill_customer_advance_allocations_bill_status
  on public.sales_bill_customer_advance_allocations(sales_bill_id, status);

create index if not exists idx_sales_bill_customer_advance_allocations_advance_status
  on public.sales_bill_customer_advance_allocations(customer_advance_doc_no, status);

create index if not exists idx_sales_bill_customer_advance_allocations_customer_status
  on public.sales_bill_customer_advance_allocations(customer_id, status)
  where customer_id is not null;
