create table if not exists public.po_sell_allocation_logs (
  event_key text not null default ('POSALLOC-'::text || gen_random_uuid()::text),
  action text not null,
  po_sell_doc_no text not null,
  sales_bill_doc_no text null,
  sales_bill_line_no integer null,
  product_code_snapshot text null,
  product_name_snapshot text null,
  allocated_qty numeric not null default 0,
  allocated_amount numeric not null default 0,
  unit_price_snapshot numeric not null default 0,
  from_remaining_qty numeric null,
  to_remaining_qty numeric null,
  note text null,
  meta jsonb null,
  created_at timestamptz not null default now(),
  created_by text null,
  id bigint generated by default as identity primary key,
  po_sell_id bigint not null references public.po_sells(id) on delete restrict,
  sales_bill_id bigint null references public.sales_bills(id) on delete set null,
  sales_bill_line_id bigint null references public.sales_bill_lines(id) on delete set null,
  product_id bigint null references public.products(id) on delete set null
);

create unique index if not exists idx_po_sell_allocation_logs_event_key
  on public.po_sell_allocation_logs(event_key);

create index if not exists idx_po_sell_allocation_logs_po_created
  on public.po_sell_allocation_logs(po_sell_id, created_at desc);

create index if not exists idx_po_sell_allocation_logs_sales_bill
  on public.po_sell_allocation_logs(sales_bill_id);

create index if not exists idx_po_sell_allocation_logs_product
  on public.po_sell_allocation_logs(product_id);

with active_allocations as (
  select
    a.id,
    a.po_sell_id,
    ps.doc_no as po_sell_doc_no,
    a.sales_bill_id,
    sb.doc_no as sales_bill_doc_no,
    a.sales_bill_line_id,
    a.sales_line_no as sales_bill_line_no,
    a.product_id,
    a.product_code_snapshot,
    a.product_name_snapshot,
    a.allocated_qty,
    a.allocated_amount,
    a.unit_price as unit_price_snapshot,
    a.created_at,
    a.created_by,
    row_number() over (
      partition by a.po_sell_id
      order by a.created_at, sb.doc_no, a.sales_line_no, a.id
    ) as seq
  from public.sales_bill_po_sell_allocations a
  join public.po_sells ps on ps.id = a.po_sell_id
  join public.sales_bills sb on sb.id = a.sales_bill_id
  where a.po_sell_id is not null
    and a.allocation_type = 'PO_SELL'
)
insert into public.po_sell_allocation_logs (
  event_key,
  action,
  po_sell_doc_no,
  sales_bill_doc_no,
  sales_bill_line_no,
  product_code_snapshot,
  product_name_snapshot,
  allocated_qty,
  allocated_amount,
  unit_price_snapshot,
  meta,
  created_at,
  created_by,
  po_sell_id,
  sales_bill_id,
  sales_bill_line_id,
  product_id
)
select
  'POSALLOC-' || po_sell_doc_no || '-' || lpad(seq::text, 4, '0') as event_key,
  'allocated_to_sales_bill' as action,
  po_sell_doc_no,
  sales_bill_doc_no,
  sales_bill_line_no,
  product_code_snapshot,
  product_name_snapshot,
  allocated_qty,
  allocated_amount,
  unit_price_snapshot,
  jsonb_build_object('source', 'migration_backfill', 'salesBillPoSellAllocationId', id::text) as meta,
  coalesce(created_at, now()),
  created_by,
  po_sell_id,
  sales_bill_id,
  sales_bill_line_id,
  product_id
from active_allocations
on conflict (event_key) do nothing;
