create table if not exists public.sales_plans (
  id bigint generated by default as identity primary key,
  plan_no text not null unique,
  plan_month date not null,
  product_id bigint not null references public.products(id) on delete restrict,
  customer_id bigint not null references public.customers(id) on delete restrict,
  channel_id bigint references public.sales_channels(id) on delete restrict,
  containers numeric not null check (containers > 0),
  kg_per_container numeric not null check (kg_per_container > 0),
  total_kg numeric not null check (total_kg > 0),
  lme_cf numeric not null check (lme_cf > 0),
  fx_rate numeric not null check (fx_rate > 0),
  sell_pct_lme numeric not null check (sell_pct_lme > 0),
  sell_price numeric not null check (sell_price > 0),
  status text not null default 'draft' check (status in ('draft', 'locked', 'po_created', 'cancelled')),
  po_sell_id bigint references public.po_sells(id) on delete restrict,
  locked_at timestamptz,
  locked_by text,
  created_at timestamptz not null default now(),
  created_by text not null,
  updated_at timestamptz not null default now(),
  updated_by text not null
);

create index if not exists idx_sales_plans_month_status on public.sales_plans(plan_month, status);
create index if not exists idx_sales_plans_product_month on public.sales_plans(product_id, plan_month);
create unique index if not exists uq_sales_plans_po_sell_id on public.sales_plans(po_sell_id) where po_sell_id is not null;
