alter table public.sales_bills
  add column if not exists cancel_note text,
  add column if not exists cancelled_at timestamptz,
  add column if not exists cancelled_by text;

create table if not exists public.sales_bill_status_logs (
  event_key text not null default ('SBSTATUS-'::text || gen_random_uuid()::text),
  action text not null,
  sales_bill_doc_no text not null,
  total_amount_snapshot numeric not null default 0,
  received_amount_snapshot numeric not null default 0,
  receivable_balance_snapshot numeric not null default 0,
  from_status text null,
  to_status text not null,
  note text null,
  meta jsonb null,
  created_at timestamptz not null default now(),
  created_by text null,
  id bigint generated by default as identity primary key,
  sales_bill_id bigint not null references public.sales_bills(id) on delete restrict
);

create unique index if not exists idx_sales_bill_status_logs_event_key
  on public.sales_bill_status_logs(event_key);

create index if not exists idx_sales_bill_status_logs_bill_created
  on public.sales_bill_status_logs(sales_bill_id, created_at desc);

create index if not exists idx_sales_bill_status_logs_doc_no
  on public.sales_bill_status_logs(sales_bill_doc_no);

create index if not exists idx_sales_bill_status_logs_action
  on public.sales_bill_status_logs(action);

with status_events as (
  select
    sb.id as sales_bill_id,
    sb.doc_no as sales_bill_doc_no,
    'created'::text as action,
    null::text as from_status,
    coalesce(sb.status, 'open') as to_status,
    coalesce(sb.total_amount, 0) as total_amount_snapshot,
    coalesce(sb.received_amount, 0) as received_amount_snapshot,
    coalesce(sb.receivable_balance, 0) as receivable_balance_snapshot,
    coalesce(sb.created_at, now()) as created_at,
    sb.created_by as created_by,
    jsonb_build_object('source', 'migration_backfill') as meta,
    1 as sort_order
  from public.sales_bills sb
  where not exists (
    select 1
    from public.sales_bill_status_logs existing
    where existing.sales_bill_id = sb.id
  )

  union all

  select
    sb.id as sales_bill_id,
    sb.doc_no as sales_bill_doc_no,
    'cancelled'::text as action,
    'unreceived'::text as from_status,
    'cancelled'::text as to_status,
    coalesce(sb.total_amount, 0) as total_amount_snapshot,
    coalesce(sb.received_amount, 0) as received_amount_snapshot,
    coalesce(sb.receivable_balance, 0) as receivable_balance_snapshot,
    coalesce(sb.cancelled_at, sb.updated_at, sb.created_at, now()) as created_at,
    coalesce(sb.cancelled_by, sb.updated_by) as created_by,
    jsonb_build_object('source', 'migration_backfill', 'cancelNote', sb.cancel_note) as meta,
    2 as sort_order
  from public.sales_bills sb
  where (sb.status = 'cancelled' or sb.cancelled_at is not null)
    and not exists (
      select 1
      from public.sales_bill_status_logs existing
      where existing.sales_bill_id = sb.id
        and existing.action = 'cancelled'
    )
),
numbered_status_events as (
  select
    status_events.*,
    row_number() over (
      partition by sales_bill_id
      order by created_at, sort_order, action
    ) as seq
  from status_events
)
insert into public.sales_bill_status_logs (
  event_key,
  action,
  sales_bill_doc_no,
  total_amount_snapshot,
  received_amount_snapshot,
  receivable_balance_snapshot,
  from_status,
  to_status,
  meta,
  created_at,
  created_by,
  sales_bill_id
)
select
  'SBSTATUS-' || sales_bill_doc_no || '-' || lpad(seq::text, 4, '0') as event_key,
  action,
  sales_bill_doc_no,
  total_amount_snapshot,
  received_amount_snapshot,
  receivable_balance_snapshot,
  from_status,
  to_status,
  meta,
  created_at,
  created_by,
  sales_bill_id
from numbered_status_events
on conflict (event_key) do nothing;
