create table if not exists public.director_employee_bank_accounts (
  id bigint generated by default as identity primary key,
  code text not null unique,
  director_id bigint not null references public.director_employees(id) on delete cascade,
  source_type text not null default 'OUTSIDE_COMPANY',
  linked_account_id bigint references public.accounts(id),
  bank_name text,
  account_name text,
  account_no text,
  bank_branch text,
  is_primary boolean default false,
  active boolean default true,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  constraint director_employee_bank_accounts_source_type_check
    check (source_type in ('IN_COMPANY', 'OUTSIDE_COMPANY')),
  constraint director_employee_bank_accounts_source_contract_check
    check (
      (source_type = 'IN_COMPANY' and linked_account_id is not null)
      or
      (source_type = 'OUTSIDE_COMPANY' and linked_account_id is null)
    )
);

create index if not exists idx_director_employee_bank_accounts_director
  on public.director_employee_bank_accounts(director_id);

create index if not exists idx_director_employee_bank_accounts_account
  on public.director_employee_bank_accounts(account_no);

create index if not exists idx_director_employee_bank_accounts_linked_account
  on public.director_employee_bank_accounts(linked_account_id);

insert into public.director_employee_bank_accounts (
  code,
  director_id,
  source_type,
  bank_name,
  account_name,
  account_no,
  bank_branch,
  is_primary,
  active,
  created_at,
  updated_at
)
select
  de.code || '-BA001',
  de.id,
  'OUTSIDE_COMPANY',
  de.bank_name,
  de.bank_account_name,
  de.account_no,
  de.bank_branch,
  true,
  true,
  now(),
  now()
from public.director_employees de
where nullif(trim(coalesce(de.account_no, de.bank_account, '')), '') is not null
  and not exists (
    select 1
    from public.director_employee_bank_accounts existing
    where existing.director_id = de.id
  );
