alter table public.receipt_vouchers
  add column if not exists status text not null default 'active',
  add column if not exists cancel_note text,
  add column if not exists cancelled_at timestamptz,
  add column if not exists cancelled_by text;

alter table public.receipt_vouchers
  drop constraint if exists receipt_vouchers_status_check;

alter table public.receipt_vouchers
  add constraint receipt_vouchers_status_check
  check (status in ('active', 'cancelled'));

create index if not exists idx_receipt_vouchers_status
  on public.receipt_vouchers(status);

create index if not exists idx_receipt_vouchers_cancelled_at
  on public.receipt_vouchers(cancelled_at)
  where cancelled_at is not null;

create table if not exists public.receipt_voucher_status_logs (
  event_key text not null default ('RVLOG-'::text || gen_random_uuid()::text),
  receipt_voucher_id bigint not null references public.receipt_vouchers(id) on delete restrict,
  receipt_voucher_doc_no text not null,
  action text not null,
  from_status text,
  to_status text not null,
  total_amount_snapshot numeric not null default 0,
  note text,
  meta jsonb,
  created_at timestamptz not null default now(),
  created_by text,
  id bigint generated by default as identity primary key,
  constraint receipt_voucher_status_logs_event_key_key unique (event_key),
  constraint receipt_voucher_status_logs_status_check check (
    (from_status is null or from_status in ('active', 'cancelled'))
    and to_status in ('active', 'cancelled')
  )
);

create index if not exists idx_receipt_voucher_status_logs_voucher_created
  on public.receipt_voucher_status_logs(receipt_voucher_id, created_at desc);

create index if not exists idx_receipt_voucher_status_logs_doc_no
  on public.receipt_voucher_status_logs(receipt_voucher_doc_no);

create index if not exists idx_receipt_voucher_status_logs_action
  on public.receipt_voucher_status_logs(action);

insert into public.receipt_voucher_status_logs (
  receipt_voucher_id,
  receipt_voucher_doc_no,
  action,
  from_status,
  to_status,
  total_amount_snapshot,
  note,
  created_at,
  created_by
)
select
  rv.id,
  rv.doc_no,
  'created',
  null,
  rv.status,
  coalesce(rv.total_amount, 0),
  null,
  coalesce(rv.created_at, now()),
  rv.created_by
from public.receipt_vouchers rv
where rv.doc_no is not null
  and not exists (
    select 1
    from public.receipt_voucher_status_logs log
    where log.receipt_voucher_id = rv.id
      and log.action = 'created'
  );
