alter table public.weight_ticket_lines
  add column if not exists warehouse_id bigint;

alter table public.weight_ticket_lines
  add constraint weight_ticket_lines_warehouse_id_fkey
  foreign key (warehouse_id)
  references public.warehouses(id)
  on update no action
  on delete no action;

create index if not exists idx_weight_ticket_lines_warehouse
  on public.weight_ticket_lines(warehouse_id);

create table public.stock_holds (
  hold_key text not null default ('STH-'::text || gen_random_uuid()::text),
  source_type text not null default 'WTO',
  source_doc_no text not null,
  source_line_no integer,
  qty numeric not null default 0,
  status text not null default 'active',
  held_at timestamptz not null default now(),
  released_at timestamptz,
  consumed_at timestamptz,
  cancelled_at timestamptz,
  released_by text,
  consumed_by text,
  cancelled_by text,
  release_reason text,
  consumed_by_ref_type text,
  consumed_by_ref_no text,
  note text,
  meta jsonb,
  created_at timestamptz not null default now(),
  created_by text,
  updated_at timestamptz,
  updated_by text,
  id bigint generated by default as identity primary key,
  weight_ticket_id bigint not null references public.weight_tickets(id) on update no action on delete restrict,
  weight_ticket_line_id bigint references public.weight_ticket_lines(id) on update no action on delete set null,
  product_id bigint not null references public.products(id) on update no action on delete restrict,
  branch_id bigint not null references public.branches(id) on update no action on delete restrict,
  warehouse_id bigint not null references public.warehouses(id) on update no action on delete restrict,
  constraint stock_holds_hold_key_key unique (hold_key),
  constraint stock_holds_source_type_check check (source_type in ('WTO')),
  constraint stock_holds_status_check check (status in ('active', 'consumed', 'released', 'cancelled')),
  constraint stock_holds_qty_check check (qty >= 0),
  constraint stock_holds_release_timestamp_check check (
    (status <> 'released' and released_at is null)
    or (status = 'released' and released_at is not null)
  ),
  constraint stock_holds_consume_timestamp_check check (
    (status <> 'consumed' and consumed_at is null)
    or (status = 'consumed' and consumed_at is not null)
  ),
  constraint stock_holds_cancel_timestamp_check check (
    (status <> 'cancelled' and cancelled_at is null)
    or (status = 'cancelled' and cancelled_at is not null)
  )
);

create index idx_stock_holds_active_lookup
  on public.stock_holds(branch_id, product_id, warehouse_id)
  where status = 'active';

create index idx_stock_holds_ticket_status
  on public.stock_holds(weight_ticket_id, status);

create index idx_stock_holds_source_doc
  on public.stock_holds(source_type, source_doc_no);

create index idx_stock_holds_line
  on public.stock_holds(weight_ticket_line_id);

alter table public.stock_holds enable row level security;

comment on table public.stock_holds is
  'Reservation facts for outbound stock documents. WTO creates active holds; SB consumes holds and writes stock_ledger.';

comment on column public.weight_ticket_lines.warehouse_id is
  'Intended stock location for WTO lines. WTI lines normally leave this null.';

comment on column public.stock_holds.qty is
  'Held quantity in the same operational unit used by stock balance and WTO net weight.';
