create table if not exists public.stock_issue_status_logs (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  stock_issue_id bigint not null references public.stock_issues(id) on delete restrict,
  stock_issue_doc_no text not null,
  action text not null,
  from_status text,
  to_status text not null,
  total_cost_snapshot numeric not null default 0,
  total_est_amount_snapshot numeric not null default 0,
  note text,
  meta jsonb,
  created_at timestamptz not null default now(),
  created_by text
);

create index if not exists idx_stock_issue_status_logs_issue_created
  on public.stock_issue_status_logs (stock_issue_id, created_at desc);

create index if not exists idx_stock_issue_status_logs_doc_no
  on public.stock_issue_status_logs (stock_issue_doc_no);

create index if not exists idx_stock_issue_status_logs_action
  on public.stock_issue_status_logs (action);

with ordered_stock_issues as (
  select
    si.id,
    si.doc_no,
    coalesce(si.status, 'pending') as status,
    coalesce(si.total_cost, 0) as total_cost,
    coalesce(si.total_est_amount, 0) as total_est_amount,
    si.created_at,
    si.created_by,
    row_number() over (partition by si.doc_no order by si.id) as seq
  from public.stock_issues si
)
insert into public.stock_issue_status_logs (
  event_key,
  stock_issue_id,
  stock_issue_doc_no,
  action,
  from_status,
  to_status,
  total_cost_snapshot,
  total_est_amount_snapshot,
  note,
  meta,
  created_at,
  created_by
)
select
  'PSALELOG-' || doc_no || '-' || lpad(seq::text, 4, '0'),
  id,
  doc_no,
  case
    when status = 'converted' then 'converted'
    when status = 'cancelled' then 'cancelled'
    else 'created'
  end,
  null,
  status,
  total_cost,
  total_est_amount,
  null,
  jsonb_build_object('reason', 'migration_backfill'),
  coalesce(created_at, now()),
  created_by
from ordered_stock_issues osi
where not exists (
  select 1
  from public.stock_issue_status_logs existing
  where existing.stock_issue_id = osi.id
);
