alter table public.grade_adjustments
  add column if not exists status text not null default 'posted',
  add column if not exists cost_status text not null default 'allocated',
  add column if not exists source_type text not null default 'Manual',
  add column if not exists allocation_method text,
  add column if not exists branch_id bigint references public.branches(id),
  add column if not exists source_product_id bigint references public.products(id),
  add column if not exists target_product_id bigint references public.products(id),
  add column if not exists source_qty numeric,
  add column if not exists target_qty numeric,
  add column if not exists source_lot_no text,
  add column if not exists target_lot_no text,
  add column if not exists reversed_at timestamptz,
  add column if not exists reversed_by text;

update public.grade_adjustments
set
  source_product_id = coalesce(source_product_id, product_id),
  source_qty = coalesce(source_qty, abs(qty_diff)),
  target_qty = coalesce(target_qty, greatest(0::numeric, abs(qty_diff) + qty_diff)),
  allocation_method = coalesce(allocation_method, 'LEGACY_WAC')
where source_product_id is null
   or source_qty is null
   or target_qty is null
   or allocation_method is null;

create table if not exists public.stock_cost_pool_entries (
  id bigint generated by default as identity primary key,
  pool_key text not null unique default ('SCP-'::text || gen_random_uuid()::text),
  source_type text not null,
  source_ref_type text not null,
  source_ref_id text,
  source_ref_no text,
  source_line_id text,
  source_ledger_id bigint references public.stock_ledger(id) on delete set null,
  regrade_adjustment_id bigint references public.grade_adjustments(id) on delete set null,
  date date not null,
  branch_id bigint references public.branches(id),
  warehouse_id bigint references public.warehouses(id),
  product_id bigint not null references public.products(id),
  lot_no text,
  original_qty numeric not null,
  allocated_qty numeric not null default 0,
  released_qty numeric not null default 0,
  unit_cost numeric not null,
  original_value numeric not null,
  status text not null default 'Available',
  notes text,
  created_at timestamptz default now(),
  created_by text,
  updated_at timestamptz,
  updated_by text,
  constraint stock_cost_pool_entries_source_type_check check (source_type in ('Legacy_Ledger', 'Purchase', 'Production', 'Regrade', 'Conversion', 'Adjustment')),
  constraint stock_cost_pool_entries_status_check check (status in ('Available', 'Partially Used', 'Fully Used', 'Released', 'Cancelled')),
  constraint stock_cost_pool_entries_qty_check check (original_qty > 0 and allocated_qty >= 0 and released_qty >= 0 and allocated_qty + released_qty <= original_qty + 0.000001),
  constraint stock_cost_pool_entries_cost_check check (unit_cost >= 0 and original_value >= 0)
);

create table if not exists public.stock_cost_pool_allocations (
  id bigint generated by default as identity primary key,
  allocation_key text not null unique default ('SCA-'::text || gen_random_uuid()::text),
  allocation_type text not null,
  status text not null default 'active',
  grade_adjustment_id bigint not null references public.grade_adjustments(id) on delete restrict,
  source_pool_entry_id bigint not null references public.stock_cost_pool_entries(id) on delete restrict,
  target_pool_entry_id bigint references public.stock_cost_pool_entries(id) on delete set null,
  line_no integer not null default 1,
  allocation_method text not null,
  qty numeric not null,
  unit_cost numeric not null,
  total_cost numeric not null,
  created_at timestamptz default now(),
  created_by text,
  reversed_at timestamptz,
  reversed_by text,
  notes text,
  constraint stock_cost_pool_allocations_type_check check (allocation_type in ('GA_SOURCE_CONSUME')),
  constraint stock_cost_pool_allocations_status_check check (status in ('active', 'reversed')),
  constraint stock_cost_pool_allocations_qty_check check (qty > 0 and unit_cost >= 0 and total_cost >= 0)
);

create index if not exists idx_stock_cost_pool_entries_available
  on public.stock_cost_pool_entries (product_id, branch_id, warehouse_id, status, date, id)
  where status in ('Available', 'Partially Used');

create index if not exists idx_stock_cost_pool_entries_regrade
  on public.stock_cost_pool_entries (regrade_adjustment_id)
  where regrade_adjustment_id is not null;

create index if not exists idx_stock_cost_pool_entries_ref
  on public.stock_cost_pool_entries (source_ref_type, source_ref_no);

create unique index if not exists idx_stock_cost_pool_entries_backfill_dimension
  on public.stock_cost_pool_entries (source_ref_type, product_id, branch_id, warehouse_id, coalesce(lot_no, ''))
  where source_ref_type = 'STOCK_BALANCE_BACKFILL';

create index if not exists idx_stock_cost_pool_allocations_adjustment
  on public.stock_cost_pool_allocations (grade_adjustment_id, status);

create index if not exists idx_stock_cost_pool_allocations_source
  on public.stock_cost_pool_allocations (source_pool_entry_id, status);

create index if not exists idx_grade_adjustments_status_date
  on public.grade_adjustments (status, date desc, created_at desc, id desc);

insert into public.stock_cost_pool_entries (
  source_type,
  source_ref_type,
  source_ref_no,
  date,
  branch_id,
  warehouse_id,
  product_id,
  lot_no,
  original_qty,
  unit_cost,
  original_value,
  status,
  notes
)
select
  'Legacy_Ledger',
  'STOCK_BALANCE_BACKFILL',
  'STOCK-BALANCE-' || coalesce(p.code, sl.product_id::text),
  max(sl.date),
  sl.branch_id,
  sl.warehouse_id,
  sl.product_id,
  nullif(sl.lot_no, ''),
  sum(coalesce(sl.qty_in, 0) - coalesce(sl.qty_out, 0)) as qty,
  sum(coalesce(sl.value_in, 0) - coalesce(sl.value_out, 0)) / nullif(sum(coalesce(sl.qty_in, 0) - coalesce(sl.qty_out, 0)), 0) as unit_cost,
  sum(coalesce(sl.value_in, 0) - coalesce(sl.value_out, 0)) as value,
  'Available',
  'Backfilled from current stock balance for Grade Adjustment cost pool'
from public.stock_ledger sl
left join public.products p on p.id = sl.product_id
where sl.product_id is not null
group by sl.branch_id, sl.warehouse_id, sl.product_id, nullif(sl.lot_no, ''), p.code
having sum(coalesce(sl.qty_in, 0) - coalesce(sl.qty_out, 0)) > 0.000001
   and sum(coalesce(sl.value_in, 0) - coalesce(sl.value_out, 0)) > 0.000001
on conflict do nothing;
