alter table public.depreciations
  add column if not exists period_year integer,
  add column if not exists period_month integer,
  add column if not exists status text not null default 'posted',
  add column if not exists posted_at timestamptz not null default now(),
  add column if not exists posted_by text,
  add column if not exists updated_at timestamptz not null default now(),
  add column if not exists updated_by text,
  add column if not exists reversed_at timestamptz,
  add column if not exists reversed_by text,
  add column if not exists reversal_reason text;

update public.depreciations
set
  period_year = coalesce(period_year, extract(year from date)::integer),
  period_month = coalesce(period_month, extract(month from date)::integer),
  posted_at = coalesce(posted_at, created_at, now())
where date is not null
  and (period_year is null or period_month is null);

alter table public.depreciations
  drop constraint if exists chk_depreciations_period_month,
  add constraint chk_depreciations_period_month check (period_month is null or period_month between 1 and 12);

alter table public.depreciations
  drop constraint if exists chk_depreciations_status,
  add constraint chk_depreciations_status check (status in ('posted', 'reversed'));

create index if not exists idx_depreciations_asset_period_status
  on public.depreciations (asset_id, period_year, period_month, status);

create index if not exists idx_depreciations_status_date
  on public.depreciations (status, date desc, id desc);

create table if not exists public.asset_disposals (
  id bigint generated by default as identity primary key,
  disposal_no text not null,
  asset_id bigint not null references public.assets(id) on update no action on delete restrict,
  disposal_date date not null,
  disposal_type text not null,
  selling_price numeric not null default 0,
  book_value_at_disposal numeric not null default 0,
  gain_loss numeric not null default 0,
  customer_id bigint null references public.customers(id) on update no action on delete restrict,
  customer_receipt_id bigint null references public.customer_receipts(id) on update no action on delete restrict,
  receipt_ref_no text null,
  reason text null,
  notes text null,
  status text not null default 'draft',
  approved_at timestamptz null,
  approved_by text null,
  created_at timestamptz not null default now(),
  created_by text null,
  updated_at timestamptz not null default now(),
  updated_by text null,
  reversed_at timestamptz null,
  reversed_by text null,
  reversal_reason text null,
  constraint uq_asset_disposals_disposal_no unique (disposal_no),
  constraint chk_asset_disposals_type check (disposal_type in ('Sale', 'Scrap', 'Write Off', 'Lost', 'Other')),
  constraint chk_asset_disposals_status check (status in ('draft', 'approved', 'reversed')),
  constraint chk_asset_disposals_amounts check (selling_price >= 0 and book_value_at_disposal >= 0)
);

create index if not exists idx_asset_disposals_asset_date
  on public.asset_disposals (asset_id, disposal_date desc, id desc);

create index if not exists idx_asset_disposals_status_date
  on public.asset_disposals (status, disposal_date desc, id desc);

create index if not exists idx_asset_disposals_customer_date
  on public.asset_disposals (customer_id, disposal_date desc, id desc)
  where customer_id is not null;

create index if not exists idx_asset_disposals_receipt
  on public.asset_disposals (customer_receipt_id)
  where customer_receipt_id is not null;
