create table if not exists public.weight_ticket_notification_logs (
  id bigint generated by default as identity primary key,
  weight_ticket_id bigint not null references public.weight_tickets(id) on delete cascade,
  delivery_channel text not null default 'line',
  target_id text,
  status text not null,
  pdf_storage_bucket text,
  pdf_storage_key text,
  pdf_url text,
  line_request_id text,
  custom_message text,
  error_message text,
  requested_by text,
  sent_at timestamptz,
  created_at timestamptz not null default now(),
  constraint weight_ticket_notification_logs_channel_check check (delivery_channel in ('line')),
  constraint weight_ticket_notification_logs_status_check check (status in ('sent', 'failed'))
);

create index if not exists idx_weight_ticket_notification_logs_ticket
  on public.weight_ticket_notification_logs (weight_ticket_id, created_at desc);

create index if not exists idx_weight_ticket_notification_logs_status
  on public.weight_ticket_notification_logs (status, created_at desc);

alter table public.weight_ticket_notification_logs enable row level security;

grant select, insert, update, delete on public.weight_ticket_notification_logs to service_role;
grant usage, select on sequence public.weight_ticket_notification_logs_id_seq to service_role;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('weight-ticket-pdfs', 'weight-ticket-pdfs', true, 10485760, array['application/pdf'])
on conflict (id) do update
set public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;
