-- Create system_settings table
create table if not exists public.system_settings (
  id bigint generated by default as identity primary key,
  key text not null unique,
  value text,
  description text,
  updated_at timestamptz not null default now(),
  updated_by text
);

-- Enable RLS
alter table public.system_settings enable row level security;

-- Pre-populate with keys for LINE messaging configurations if not already exists
insert into public.system_settings (key, description) values
  ('LINE_CHANNEL_ACCESS_TOKEN', 'LINE Messaging API Channel Access Token (long-lived)'),
  ('LINE_CHANNEL_SECRET', 'LINE Channel Secret for webhook verification'),
  ('LINE_DEFAULT_TARGET_ID', 'Default LINE Group or User ID to send push notifications to'),
  ('WEIGHT_TICKET_PDF_BUCKET', 'Supabase Storage bucket name for weight ticket PDFs'),
  ('NEXT_PUBLIC_APP_URL', 'Public app base URL for link references')
on conflict (key) do nothing;
