
-- This is a per-user working copy only. It is deliberately separate from
-- weight_tickets so incomplete input never receives a document number,
-- creates stock state, or becomes a business/audit source of truth.
create table public.weight_ticket_form_drafts (
  id bigint generated by default as identity primary key,
  app_user_id bigint not null references public.app_users(id) on delete cascade,
  scope_key text not null check (char_length(scope_key) between 1 and 160),
  ticket_type text not null check (ticket_type in ('WTI', 'WTO')),
  payload jsonb not null,
  revision integer not null default 1 check (revision > 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint uq_weight_ticket_form_drafts_owner_scope unique (app_user_id, scope_key)
);

create index idx_weight_ticket_form_drafts_owner_updated
  on public.weight_ticket_form_drafts (app_user_id, updated_at desc);

comment on table public.weight_ticket_form_drafts is
  'Private incomplete WTI/WTO form snapshots. Not a business document, inventory source, audit log, or LINE notification source.';

alter table public.weight_ticket_form_drafts enable row level security;

-- The active app accesses this table only through authenticated server routes.
-- Keeping the Data API roles unprivileged prevents a client from bypassing
-- the route-level permission and ownership checks.
revoke all on table public.weight_ticket_form_drafts from anon, authenticated;
