create table if not exists public.customer_receipts (
  id bigint generated by default as identity primary key,
  doc_no text not null,
  date date not null,
  gross_amount numeric not null default 0,
  discount_total numeric not null default 0,
  bank_fee_total numeric not null default 0,
  withholding_tax_total numeric not null default 0,
  net_cash_in numeric not null default 0,
  status text not null default 'active',
  payment_method_code_snapshot text not null,
  payment_method_name_snapshot text not null,
  customer_code_snapshot text not null,
  customer_name_snapshot text not null,
  account_code_snapshot text not null,
  account_name_snapshot text not null,
  bank_statement_doc_no text,
  notes text,
  cancel_reason text,
  cancelled_at timestamptz,
  cancelled_by text,
  created_at timestamptz not null default now(),
  created_by text,
  updated_at timestamptz not null default now(),
  updated_by text,
  version integer not null default 1,
  customer_id bigint not null references public.customers(id) on delete restrict on update no action,
  account_id bigint not null references public.accounts(id) on delete restrict on update no action,
  branch_id bigint references public.branches(id) on delete restrict on update no action,
  payment_method_id bigint not null references public.payment_methods(id) on delete restrict on update no action,
  bank_statement_id bigint unique references public.bank_statement(id) on delete set null on update no action,
  constraint customer_receipts_doc_no_key unique (doc_no),
  constraint customer_receipts_status_chk check (status in ('active', 'cancelled')),
  constraint customer_receipts_amount_nonnegative_chk check (
    gross_amount >= 0
    and discount_total >= 0
    and bank_fee_total >= 0
    and withholding_tax_total >= 0
    and net_cash_in >= 0
  ),
  constraint customer_receipts_net_cash_chk check (
    net_cash_in = gross_amount - bank_fee_total - withholding_tax_total
  )
);

create index if not exists idx_customer_receipts_date on public.customer_receipts(date desc);
create index if not exists idx_customer_receipts_customer_date on public.customer_receipts(customer_id, date desc);
create index if not exists idx_customer_receipts_account_date on public.customer_receipts(account_id, date desc);
create index if not exists idx_customer_receipts_branch_date on public.customer_receipts(branch_id, date desc) where branch_id is not null;
create index if not exists idx_customer_receipts_status on public.customer_receipts(status);
create index if not exists idx_customer_receipts_bank_statement on public.customer_receipts(bank_statement_id) where bank_statement_id is not null;

create table if not exists public.customer_receipt_allocations (
  id bigint generated by default as identity primary key,
  receipt_id bigint not null references public.customer_receipts(id) on delete restrict on update no action,
  sales_bill_id bigint not null references public.sales_bills(id) on delete restrict on update no action,
  receipt_line_id bigint unique references public.receipts(id) on delete set null on update no action,
  line_no integer not null,
  sales_bill_doc_no_snapshot text not null,
  customer_code_snapshot text not null,
  receipt_amount numeric not null default 0,
  discount_amount numeric not null default 0,
  withholding_tax_amount numeric not null default 0,
  allocated_ar_amount numeric not null default 0,
  outstanding_before numeric not null default 0,
  outstanding_after numeric not null default 0,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  created_by text,
  updated_at timestamptz not null default now(),
  updated_by text,
  version integer not null default 1,
  constraint customer_receipt_allocations_line_unique unique (receipt_id, line_no),
  constraint customer_receipt_allocations_status_chk check (status in ('active', 'cancelled')),
  constraint customer_receipt_allocations_amount_nonnegative_chk check (
    receipt_amount >= 0
    and discount_amount >= 0
    and withholding_tax_amount >= 0
    and allocated_ar_amount >= 0
    and outstanding_before >= 0
    and outstanding_after >= 0
  ),
  constraint customer_receipt_allocations_ar_amount_chk check (
    allocated_ar_amount = receipt_amount + discount_amount + withholding_tax_amount
  ),
  constraint customer_receipt_allocations_outstanding_chk check (
    outstanding_after = outstanding_before - allocated_ar_amount
  )
);

create index if not exists idx_customer_receipt_allocations_receipt on public.customer_receipt_allocations(receipt_id, line_no);
create index if not exists idx_customer_receipt_allocations_sales_bill on public.customer_receipt_allocations(sales_bill_id);
create index if not exists idx_customer_receipt_allocations_status on public.customer_receipt_allocations(status);
create index if not exists idx_customer_receipt_allocations_receipt_line on public.customer_receipt_allocations(receipt_line_id) where receipt_line_id is not null;

create table if not exists public.customer_receipt_status_logs (
  id bigint generated by default as identity primary key,
  event_key text not null unique default ('RCPLOG-'::text || gen_random_uuid()::text),
  receipt_id bigint not null references public.customer_receipts(id) on delete restrict on update no action,
  receipt_doc_no text not null,
  action text not null,
  from_status text,
  to_status text not null,
  gross_amount_snapshot numeric not null default 0,
  net_cash_in_snapshot numeric not null default 0,
  note text,
  meta jsonb,
  created_at timestamptz not null default now(),
  created_by text
);

create index if not exists idx_customer_receipt_status_logs_receipt_created on public.customer_receipt_status_logs(receipt_id, created_at desc);
create index if not exists idx_customer_receipt_status_logs_doc_no on public.customer_receipt_status_logs(receipt_doc_no);
create index if not exists idx_customer_receipt_status_logs_action on public.customer_receipt_status_logs(action);

with receipt_source as (
  select
    r.*,
    coalesce(nullif(trim(r.voucher_id), ''), r.doc_no) as group_doc_no,
    pm.id as payment_method_id,
    pm.code as payment_method_code,
    pm.name as payment_method_name,
    c.code as customer_code,
    c.name as customer_name,
    a.code as account_code,
    a.name as account_name,
    sb.doc_no as sales_bill_doc_no,
    sb.total_amount as sales_bill_total_amount,
    sum(coalesce(r.amount, 0) + coalesce(r.discount, 0) + coalesce(r.withholding_tax, 0)) over (
      partition by r.bill_id
      order by r.date, r.id
      rows between unbounded preceding and 1 preceding
    ) as allocated_before_bill
  from public.receipts r
  join public.customers c on c.id = r.customer_id and c.code is not null
  join public.accounts a on a.id = r.account_id and a.code is not null
  join public.sales_bills sb on sb.id = r.bill_id
  join public.payment_methods pm
    on pm.active = true
    and (
      pm.name = r.method
      or pm.code = upper(trim(coalesce(r.method, '')))
    )
  where coalesce(r.status, 'active') = 'active'
    and r.bill_id is not null
    and not exists (
      select 1
      from public.customer_receipts existing
      where existing.doc_no = coalesce(nullif(trim(r.voucher_id), ''), r.doc_no)
    )
),
eligible_groups as (
  select
    group_doc_no,
    min(date) as date,
    min(created_at) as created_at,
    min(created_by) as created_by,
    max(updated_at) as updated_at,
    max(updated_by) as updated_by,
    min(customer_id) as customer_id,
    min(customer_code) as customer_code,
    min(customer_name) as customer_name,
    min(account_id) as account_id,
    min(account_code) as account_code,
    min(account_name) as account_name,
    min(branch_id) as branch_id,
    min(payment_method_id) as payment_method_id,
    min(payment_method_code) as payment_method_code,
    min(payment_method_name) as payment_method_name,
    sum(coalesce(amount, 0)) as gross_amount,
    sum(coalesce(discount, 0)) as discount_total,
    sum(coalesce(bank_fee, fee, 0)) as bank_fee_total,
    sum(coalesce(withholding_tax, 0)) as withholding_tax_total,
    string_agg(distinct nullif(notes, ''), '; ' order by nullif(notes, '')) filter (where nullif(notes, '') is not null) as notes,
    count(distinct customer_id) as customer_count,
    count(distinct account_id) as account_count,
    count(distinct payment_method_id) as payment_method_count,
    count(*) filter (where bill_id is null) as missing_bill_count
  from receipt_source
  group by group_doc_no
  having count(distinct customer_id) = 1
    and count(distinct account_id) = 1
    and count(distinct payment_method_id) = 1
    and count(*) filter (where bill_id is null) = 0
),
inserted_headers as (
  insert into public.customer_receipts (
    doc_no,
    date,
    gross_amount,
    discount_total,
    bank_fee_total,
    withholding_tax_total,
    net_cash_in,
    status,
    payment_method_code_snapshot,
    payment_method_name_snapshot,
    customer_code_snapshot,
    customer_name_snapshot,
    account_code_snapshot,
    account_name_snapshot,
    notes,
    created_at,
    created_by,
    updated_at,
    updated_by,
    customer_id,
    account_id,
    branch_id,
    payment_method_id
  )
  select
    group_doc_no,
    date,
    gross_amount,
    discount_total,
    bank_fee_total,
    withholding_tax_total,
    gross_amount - bank_fee_total - withholding_tax_total,
    'active',
    payment_method_code,
    payment_method_name,
    customer_code,
    customer_name,
    account_code,
    account_name,
    notes,
    coalesce(created_at, now()),
    created_by,
    coalesce(updated_at, created_at, now()),
    updated_by,
    customer_id,
    account_id,
    branch_id,
    payment_method_id
  from eligible_groups
  on conflict (doc_no) do nothing
  returning id, doc_no, gross_amount, net_cash_in, created_by
),
allocation_source as (
  select
    h.id as receipt_id,
    h.doc_no as receipt_doc_no,
    row_number() over (partition by rs.group_doc_no order by rs.date, rs.id)::integer as line_no,
    rs.id as receipt_line_id,
    rs.bill_id as sales_bill_id,
    rs.sales_bill_doc_no,
    rs.customer_code,
    coalesce(rs.amount, 0) as receipt_amount,
    coalesce(rs.discount, 0) as discount_amount,
    coalesce(rs.withholding_tax, 0) as withholding_tax_amount,
    coalesce(rs.amount, 0) + coalesce(rs.discount, 0) + coalesce(rs.withholding_tax, 0) as allocated_ar_amount,
    greatest(0, coalesce(rs.sales_bill_total_amount, 0) - coalesce(rs.allocated_before_bill, 0)) as outstanding_before,
    greatest(0, coalesce(rs.sales_bill_total_amount, 0) - coalesce(rs.allocated_before_bill, 0) - (coalesce(rs.amount, 0) + coalesce(rs.discount, 0) + coalesce(rs.withholding_tax, 0))) as outstanding_after,
    rs.created_at,
    rs.created_by,
    rs.updated_at,
    rs.updated_by
  from receipt_source rs
  join inserted_headers h on h.doc_no = rs.group_doc_no
)
insert into public.customer_receipt_allocations (
  receipt_id,
  sales_bill_id,
  receipt_line_id,
  line_no,
  sales_bill_doc_no_snapshot,
  customer_code_snapshot,
  receipt_amount,
  discount_amount,
  withholding_tax_amount,
  allocated_ar_amount,
  outstanding_before,
  outstanding_after,
  status,
  created_at,
  created_by,
  updated_at,
  updated_by
)
select
  receipt_id,
  sales_bill_id,
  receipt_line_id,
  line_no,
  sales_bill_doc_no,
  customer_code,
  receipt_amount,
  discount_amount,
  withholding_tax_amount,
  allocated_ar_amount,
  outstanding_before,
  outstanding_after,
  'active',
  coalesce(created_at, now()),
  created_by,
  coalesce(updated_at, created_at, now()),
  updated_by
from allocation_source
on conflict (receipt_id, line_no) do nothing;

insert into public.customer_receipt_status_logs (
  event_key,
  receipt_id,
  receipt_doc_no,
  action,
  to_status,
  gross_amount_snapshot,
  net_cash_in_snapshot,
  note,
  created_by
)
select
  'customer-receipt.backfill.' || doc_no,
  id,
  doc_no,
  'backfilled',
  'active',
  gross_amount,
  net_cash_in,
  'backfilled from legacy receipts',
  created_by
from public.customer_receipts
where not exists (
  select 1
  from public.customer_receipt_status_logs existing
  where existing.event_key = 'customer-receipt.backfill.' || customer_receipts.doc_no
)
on conflict (event_key) do nothing;
