begin;

alter table public.customer_receipts
  add column if not exists source_type text not null default 'SB';

alter table public.customer_receipts
  drop constraint if exists customer_receipts_source_type_check,
  add constraint customer_receipts_source_type_check check (source_type in ('SB', 'CADV'));

create table public.customer_receipt_advance_allocations (
  id bigint generated by default as identity primary key,
  receipt_id bigint not null references public.customer_receipts(id) on delete restrict on update no action,
  customer_advance_id bigint not null references public.customer_advances(id) on delete restrict on update no action,
  line_no integer not null,
  customer_advance_doc_no_snapshot text not null,
  customer_code_snapshot text not null,
  receipt_amount numeric(18, 2) not null default 0,
  received_before numeric(18, 2) not null default 0,
  received_after numeric(18, 2) not null default 0,
  available_before numeric(18, 2) not null default 0,
  available_after numeric(18, 2) not null default 0,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  created_by text,
  updated_at timestamptz not null default now(),
  updated_by text,
  version integer not null default 1,
  constraint customer_receipt_advance_allocations_line_key unique (receipt_id, line_no),
  constraint customer_receipt_advance_allocations_line_no_check check (line_no > 0),
  constraint customer_receipt_advance_allocations_amounts_check check (
    receipt_amount > 0
    and received_before >= 0
    and received_after >= 0
    and available_before >= 0
    and available_after >= 0
  ),
  constraint customer_receipt_advance_allocations_status_check check (status in ('active', 'cancelled'))
);

create index idx_customer_receipt_advance_allocations_receipt
  on public.customer_receipt_advance_allocations (receipt_id, line_no);
create index idx_customer_receipt_advance_allocations_advance
  on public.customer_receipt_advance_allocations (customer_advance_id, status, created_at desc);
create index idx_customer_receipt_advance_allocations_active_advance
  on public.customer_receipt_advance_allocations (customer_advance_id)
  where status = 'active';

commit;
