create table if not exists public.production_order_status_logs (
  event_key text not null default ('POSTATUS-'::text || gen_random_uuid()::text),
  action text not null,
  order_doc_no text not null,
  from_status text null,
  to_status text not null,
  note text null,
  meta jsonb null,
  created_at timestamptz not null default now(),
  created_by text null,
  id bigint generated by default as identity primary key,
  order_id bigint not null references public.production_orders(id) on delete restrict
);

create unique index if not exists idx_production_order_status_logs_event_key
  on public.production_order_status_logs(event_key);

create index if not exists idx_production_order_status_logs_order_created
  on public.production_order_status_logs(order_id, created_at desc);

create index if not exists idx_production_order_status_logs_doc_no
  on public.production_order_status_logs(order_doc_no);

create index if not exists idx_production_order_status_logs_action
  on public.production_order_status_logs(action);

alter table public.production_order_status_logs enable row level security;

alter table public.production_inputs
  add column if not exists doc_no text,
  add column if not exists status text not null default 'active',
  add column if not exists source_warehouse_id bigint references public.warehouses(id) on update no action on delete no action,
  add column if not exists wip_warehouse_id bigint references public.warehouses(id) on update no action on delete no action,
  add column if not exists lot_no text,
  add column if not exists wac_unit_cost numeric,
  add column if not exists reversed_at timestamptz,
  add column if not exists reversed_by text,
  add column if not exists reverse_reason text,
  add column if not exists reversal_doc_no text;

alter table public.production_outputs
  add column if not exists doc_no text,
  add column if not exists status text not null default 'active',
  add column if not exists category_code text,
  add column if not exists destination_warehouse_id bigint references public.warehouses(id) on update no action on delete no action,
  add column if not exists lot_no text,
  add column if not exists source_wip_qty numeric,
  add column if not exists reversed_at timestamptz,
  add column if not exists reversed_by text,
  add column if not exists reverse_reason text,
  add column if not exists reversal_doc_no text;

with numbered_inputs as (
  select
    pi.id,
    'PI' || to_char(pi.date, 'YYMM') || '-L' || lpad(row_number() over (partition by to_char(pi.date, 'YYMM') order by pi.date, pi.id)::text, 5, '0') as generated_doc_no
  from public.production_inputs pi
  where pi.doc_no is null
)
update public.production_inputs pi
set doc_no = numbered_inputs.generated_doc_no
from numbered_inputs
where pi.id = numbered_inputs.id;

update public.production_inputs pi
set
  source_warehouse_id = coalesce(pi.source_warehouse_id, po.warehouse_from_id, po.warehouse_id),
  wip_warehouse_id = coalesce(pi.wip_warehouse_id, po.warehouse_wip_id),
  wac_unit_cost = coalesce(pi.wac_unit_cost, pi.unit_cost)
from public.production_orders po
where pi.order_id = po.id;

with numbered_outputs as (
  select
    po2.id,
    'PO2' || to_char(po2.date, 'YYMM') || '-L' || lpad(row_number() over (partition by to_char(po2.date, 'YYMM') order by po2.date, po2.id)::text, 5, '0') as generated_doc_no
  from public.production_outputs po2
  where po2.doc_no is null
)
update public.production_outputs po2
set doc_no = numbered_outputs.generated_doc_no
from numbered_outputs
where po2.id = numbered_outputs.id;

update public.production_outputs po2
set category_code = poc.code
from public.production_output_categories poc
where po2.output_category = poc.id
  and po2.category_code is null;

update public.production_outputs po2
set
  destination_warehouse_id = coalesce(po2.destination_warehouse_id, po.warehouse_to_id, po.warehouse_id),
  source_wip_qty = coalesce(po2.source_wip_qty, po2.qty)
from public.production_orders po
where po2.order_id = po.id;

alter table public.production_inputs
  alter column doc_no set not null;

alter table public.production_outputs
  alter column doc_no set not null;

create unique index if not exists idx_production_inputs_doc_no
  on public.production_inputs(doc_no);

create unique index if not exists idx_production_outputs_doc_no
  on public.production_outputs(doc_no);

create unique index if not exists idx_production_inputs_reversal_doc_no
  on public.production_inputs(reversal_doc_no)
  where reversal_doc_no is not null;

create unique index if not exists idx_production_outputs_reversal_doc_no
  on public.production_outputs(reversal_doc_no)
  where reversal_doc_no is not null;

create index if not exists idx_production_inputs_status
  on public.production_inputs(status);

create index if not exists idx_production_outputs_status
  on public.production_outputs(status);

create index if not exists idx_production_outputs_category_code
  on public.production_outputs(category_code);

create index if not exists idx_production_inputs_source_wip_warehouse
  on public.production_inputs(source_warehouse_id, wip_warehouse_id);

create index if not exists idx_production_outputs_destination_warehouse
  on public.production_outputs(destination_warehouse_id);

create index if not exists idx_stock_ledger_production_ref
  on public.stock_ledger(ref_type, ref_no)
  where ref_type in ('PI', 'PI-REV', 'PO2', 'PO2-REV');

create index if not exists idx_stock_ledger_production_ref_movement
  on public.stock_ledger(ref_type, ref_no, movement_type)
  where ref_type in ('PI', 'PI-REV', 'PO2', 'PO2-REV');

create index if not exists idx_stock_ledger_stock_dimension
  on public.stock_ledger(branch_id, warehouse_id, product_id, date);

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'production_inputs_status_check') then
    alter table public.production_inputs
      add constraint production_inputs_status_check
      check (status in ('active', 'reversed'));
  end if;

  if not exists (select 1 from pg_constraint where conname = 'production_outputs_status_check') then
    alter table public.production_outputs
      add constraint production_outputs_status_check
      check (status in ('active', 'reversed'));
  end if;

  if not exists (select 1 from pg_constraint where conname = 'production_outputs_category_code_check') then
    alter table public.production_outputs
      add constraint production_outputs_category_code_check
      check (category_code is null or category_code in ('FG', 'RM', 'LOSS', 'CUSTOMER_RETURN'));
  end if;
end;
$$;

with created_events as (
  select
    po.id as order_id,
    po.doc_no as order_doc_no,
    'created'::text as action,
    null::text as from_status,
    coalesce(po.status, 'Open') as to_status,
    coalesce(po.created_at, now()) as created_at,
    nullif(po.updated_by, '') as created_by,
    jsonb_build_object('source', 'migration_backfill') as meta
  from public.production_orders po
  where not exists (
    select 1
    from public.production_order_status_logs existing
    where existing.order_id = po.id
  )
),
numbered_events as (
  select
    created_events.*,
    row_number() over (partition by order_id order by created_at, action) as seq
  from created_events
)
insert into public.production_order_status_logs (
  event_key,
  action,
  order_doc_no,
  from_status,
  to_status,
  meta,
  created_at,
  created_by,
  order_id
)
select
  'POSTATUS-' || order_doc_no || '-' || lpad(seq::text, 4, '0') as event_key,
  action,
  order_doc_no,
  from_status,
  to_status,
  meta,
  created_at,
  created_by,
  order_id
from numbered_events
on conflict (event_key) do nothing;
