begin;

-- FCD is an append-only subledger. Existing Account Master balances remain
-- outside this ledger until an explicit opening-balance reconciliation exists.

alter table public.bank_statement
  add column if not exists movement_currency_code text references public.currencies(code),
  add column if not exists native_amount_in numeric(18,2),
  add column if not exists native_amount_out numeric(18,2),
  add column if not exists book_amount_in numeric(18,2),
  add column if not exists book_amount_out numeric(18,2),
  add column if not exists book_fx_rate numeric(18,3),
  add column if not exists fx_rate_id bigint references public.fx_rates(id),
  add column if not exists source_event_type text,
  add column if not exists source_event_key text,
  add column if not exists reversal_of_id bigint references public.bank_statement(id),
  add column if not exists idempotency_key text;

alter table public.bank_statement
  drop constraint if exists bank_statement_fcd_movement_contract_chk,
  add constraint bank_statement_fcd_movement_contract_chk check (
    source_event_type is null
    or (
      nullif(btrim(source_event_type), '') is not null
      and nullif(btrim(source_event_key), '') is not null
      and movement_currency_code is not null
      and native_amount_in is not null
      and native_amount_out is not null
      and book_amount_in is not null
      and book_amount_out is not null
      and native_amount_in >= 0
      and native_amount_out >= 0
      and book_amount_in >= 0
      and book_amount_out >= 0
      and not (native_amount_in > 0 and native_amount_out > 0)
      and not (book_amount_in > 0 and book_amount_out > 0)
      and ((native_amount_in > 0) = (book_amount_in > 0))
      and ((native_amount_out > 0) = (book_amount_out > 0))
      and (book_fx_rate is null or book_fx_rate = round(book_fx_rate, 3))
    )
  );

create unique index if not exists uq_bank_statement_source_event
  on public.bank_statement (source_event_type, source_event_key)
  where source_event_type is not null and source_event_key is not null;
create unique index if not exists uq_bank_statement_idempotency_key
  on public.bank_statement (idempotency_key)
  where idempotency_key is not null;
create unique index if not exists uq_bank_statement_reversal_of
  on public.bank_statement (reversal_of_id)
  where reversal_of_id is not null;
create index if not exists idx_bank_statement_account_currency_date
  on public.bank_statement (account_id, movement_currency_code, date, id)
  where movement_currency_code is not null;

create table if not exists public.fcd_ledger_entries (
  id bigint generated by default as identity primary key,
  account_id bigint not null references public.accounts(id) on delete restrict,
  branch_id bigint references public.branches(id) on delete restrict,
  currency_code text not null references public.currencies(code),
  entry_date date not null,
  native_amount_in numeric(18,2) not null default 0,
  native_amount_out numeric(18,2) not null default 0,
  carrying_thb_in numeric(18,2) not null default 0,
  carrying_thb_out numeric(18,2) not null default 0,
  fx_rate numeric(18,3),
  fx_rate_id bigint references public.fx_rates(id),
  source_event_type text not null,
  source_event_key text not null,
  reversal_of_id bigint references public.fcd_ledger_entries(id) on delete restrict,
  bank_statement_id bigint unique references public.bank_statement(id) on delete restrict,
  idempotency_key text not null,
  created_at timestamptz not null default now(),
  created_by text,
  constraint fcd_ledger_entries_source_event_unique unique (source_event_type, source_event_key),
  constraint fcd_ledger_entries_idempotency_unique unique (idempotency_key),
  constraint fcd_ledger_entries_reversal_unique unique (reversal_of_id),
  constraint fcd_ledger_entries_amounts_chk check (
    native_amount_in >= 0
    and native_amount_out >= 0
    and carrying_thb_in >= 0
    and carrying_thb_out >= 0
    and not (native_amount_in > 0 and native_amount_out > 0)
    and not (carrying_thb_in > 0 and carrying_thb_out > 0)
    and (native_amount_in > 0 or native_amount_out > 0 or carrying_thb_in > 0 or carrying_thb_out > 0)
    and (native_amount_in = 0 or carrying_thb_in > 0)
    and (native_amount_out = 0 or carrying_thb_out > 0)
    and (fx_rate is null or fx_rate = round(fx_rate, 3))
  ),
  constraint fcd_ledger_entries_source_chk check (
    nullif(btrim(source_event_type), '') is not null
    and nullif(btrim(source_event_key), '') is not null
    and nullif(btrim(idempotency_key), '') is not null
  )
);

create index if not exists idx_fcd_ledger_account_currency_date
  on public.fcd_ledger_entries (account_id, currency_code, entry_date, id);
create index if not exists idx_fcd_ledger_source
  on public.fcd_ledger_entries (source_event_type, source_event_key);
create index if not exists idx_fcd_ledger_reversal
  on public.fcd_ledger_entries (reversal_of_id)
  where reversal_of_id is not null;

create or replace function public.validate_fcd_ledger_entry_account_currency()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  if not exists (
    select 1
    from public.accounts account
    join public.account_currency_balances currency_balance
      on currency_balance.account_id = account.id
     and currency_balance.currency_code = new.currency_code
     and currency_balance.active = true
    where account.id = new.account_id
      and account.is_fcd = true
      and account.active = true
  ) then
    raise exception 'FCD ledger account % does not support active currency %', new.account_id, new.currency_code;
  end if;

  return new;
end;
$$;

drop trigger if exists validate_fcd_ledger_entry_account_currency on public.fcd_ledger_entries;
create trigger validate_fcd_ledger_entry_account_currency
before insert or update of account_id, currency_code on public.fcd_ledger_entries
for each row execute function public.validate_fcd_ledger_entry_account_currency();

create or replace function public.enforce_fcd_ledger_available_balance()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
declare
  target_account_id bigint := coalesce(new.account_id, old.account_id);
  target_currency_code text := coalesce(new.currency_code, old.currency_code);
  native_balance numeric(18,2);
  account_has_od boolean;
begin
  select coalesce(sum(native_amount_in - native_amount_out), 0)
    into native_balance
  from public.fcd_ledger_entries
  where account_id = target_account_id
    and currency_code = target_currency_code;

  select coalesce(od_limit, 0) > 0
    into account_has_od
  from public.accounts
  where id = target_account_id;

  if native_balance < 0 and not account_has_od then
    raise exception 'FCD account % currency % has insufficient available balance', target_account_id, target_currency_code;
  end if;

  return null;
end;
$$;

drop trigger if exists enforce_fcd_ledger_available_balance on public.fcd_ledger_entries;
create constraint trigger enforce_fcd_ledger_available_balance
after insert or update or delete on public.fcd_ledger_entries
deferrable initially deferred
for each row execute function public.enforce_fcd_ledger_available_balance();

create or replace function public.prevent_fcd_ledger_entry_mutation()
returns trigger
language plpgsql
set search_path = public, pg_temp
as $$
begin
  raise exception 'FCD ledger entries are append-only; create a reversal entry instead';
end;
$$;

drop trigger if exists prevent_fcd_ledger_entry_mutation on public.fcd_ledger_entries;
create trigger prevent_fcd_ledger_entry_mutation
before update or delete on public.fcd_ledger_entries
for each row execute function public.prevent_fcd_ledger_entry_mutation();

create or replace view public.fcd_account_currency_balance_projection as
select
  ledger.account_id,
  ledger.currency_code,
  sum(ledger.native_amount_in - ledger.native_amount_out)::numeric(18,2) as native_balance,
  sum(ledger.carrying_thb_in - ledger.carrying_thb_out)::numeric(18,2) as carrying_thb_balance,
  case
    when sum(ledger.native_amount_in - ledger.native_amount_out) = 0 then null
    else round(
      sum(ledger.carrying_thb_in - ledger.carrying_thb_out)
      / sum(ledger.native_amount_in - ledger.native_amount_out),
      3
    )
  end as weighted_carrying_rate,
  max(ledger.entry_date) as last_entry_date
from public.fcd_ledger_entries ledger
group by ledger.account_id, ledger.currency_code;

alter table public.customer_receipts
  add column if not exists receipt_currency_code text references public.currencies(code),
  add column if not exists customer_transferred_native_amount numeric(18,2),
  add column if not exists received_native_amount numeric(18,2),
  add column if not exists settlement_book_amount numeric(18,2),
  add column if not exists carrying_thb_amount numeric(18,2),
  add column if not exists settlement_fx_difference numeric(18,2),
  add column if not exists settlement_difference_reason text,
  add column if not exists fx_rate numeric(18,3),
  add column if not exists fx_rate_id bigint references public.fx_rates(id),
  add column if not exists fx_rate_date date,
  add column if not exists fx_rate_source text,
  add column if not exists fx_rate_reference text,
  add column if not exists fx_rate_overridden boolean,
  add column if not exists fx_rate_override_reason text,
  add column if not exists replacement_of_id bigint references public.customer_receipts(id);

alter table public.customer_receipt_allocations
  add column if not exists native_amount_allocated numeric(18,2),
  add column if not exists settlement_book_amount numeric(18,2),
  add column if not exists settlement_fx_difference numeric(18,2),
  add column if not exists settlement_difference_reason text;

alter table public.customer_receipt_advance_allocations
  add column if not exists native_amount_allocated numeric(18,2),
  add column if not exists settlement_book_amount numeric(18,2);

create table if not exists public.customer_receipt_account_splits (
  id bigint generated by default as identity primary key,
  receipt_id bigint not null references public.customer_receipts(id) on delete restrict,
  line_no integer not null,
  account_id bigint not null references public.accounts(id) on delete restrict,
  account_code_snapshot text not null,
  account_name_snapshot text not null,
  currency_code text not null references public.currencies(code),
  received_native_amount numeric(18,2) not null,
  carrying_thb_amount numeric(18,2) not null,
  bank_statement_id bigint unique references public.bank_statement(id) on delete restrict,
  fcd_ledger_entry_id bigint unique references public.fcd_ledger_entries(id) on delete restrict,
  created_at timestamptz not null default now(),
  created_by text,
  constraint customer_receipt_account_splits_line_unique unique (receipt_id, line_no),
  constraint customer_receipt_account_splits_amount_chk check (
    received_native_amount > 0
    and carrying_thb_amount > 0
  )
);

create index if not exists idx_customer_receipt_account_splits_account_currency
  on public.customer_receipt_account_splits (account_id, currency_code);

create table if not exists public.fcd_revaluation_batches (
  id bigint generated by default as identity primary key,
  doc_no text not null unique,
  period_end date not null,
  branch_id bigint references public.branches(id) on delete restrict,
  status text not null default 'pending',
  rate_source text,
  rate_reference text,
  posted_at timestamptz,
  posted_by text,
  reversed_at timestamptz,
  reversed_by text,
  reversal_of_id bigint unique references public.fcd_revaluation_batches(id) on delete restrict,
  idempotency_key text unique,
  created_at timestamptz not null default now(),
  created_by text,
  updated_at timestamptz not null default now(),
  updated_by text,
  constraint fcd_revaluation_batches_status_chk check (status in ('pending', 'posted', 'reversed'))
);

create table if not exists public.fcd_revaluation_lines (
  id bigint generated by default as identity primary key,
  batch_id bigint not null references public.fcd_revaluation_batches(id) on delete restrict,
  account_id bigint not null references public.accounts(id) on delete restrict,
  currency_code text not null references public.currencies(code),
  native_balance numeric(18,2) not null,
  period_end date not null,
  carrying_thb_before numeric(18,2) not null,
  closing_fx_rate numeric(18,3) not null,
  fx_rate_id bigint references public.fx_rates(id),
  revalued_thb_amount numeric(18,2) not null,
  unrealized_fx_difference numeric(18,2) not null,
  fcd_ledger_entry_id bigint unique references public.fcd_ledger_entries(id) on delete restrict,
  posted boolean not null default false,
  constraint fcd_revaluation_lines_scope_unique unique (batch_id, account_id, currency_code)
);

create unique index if not exists uq_fcd_revaluation_posted_scope
  on public.fcd_revaluation_lines (account_id, currency_code, period_end)
  where posted;

create table if not exists public.fcd_conversions (
  id bigint generated by default as identity primary key,
  doc_no text not null unique,
  conversion_date date not null,
  branch_id bigint not null references public.branches(id) on delete restrict,
  source_account_id bigint not null references public.accounts(id) on delete restrict,
  source_currency_code text not null references public.currencies(code),
  destination_account_id bigint not null references public.accounts(id) on delete restrict,
  actual_thb_received numeric(18,2) not null,
  bank_fee_thb numeric(18,2) not null default 0,
  bank_reference text,
  status text not null default 'pending',
  reversal_of_id bigint unique references public.fcd_conversions(id) on delete restrict,
  idempotency_key text unique,
  created_at timestamptz not null default now(),
  created_by text,
  updated_at timestamptz not null default now(),
  updated_by text,
  constraint fcd_conversions_amount_chk check (actual_thb_received >= 0 and bank_fee_thb >= 0),
  constraint fcd_conversions_status_chk check (status in ('pending', 'active', 'cancelled'))
);

create table if not exists public.fcd_conversion_lines (
  id bigint generated by default as identity primary key,
  conversion_id bigint not null references public.fcd_conversions(id) on delete restrict,
  line_no integer not null,
  native_amount numeric(18,2) not null,
  carrying_thb_out numeric(18,2) not null,
  actual_thb_received numeric(18,2) not null,
  realized_fx_difference numeric(18,2) not null,
  source_fcd_ledger_entry_id bigint unique references public.fcd_ledger_entries(id) on delete restrict,
  source_bank_statement_id bigint unique references public.bank_statement(id) on delete restrict,
  destination_bank_statement_id bigint unique references public.bank_statement(id) on delete restrict,
  constraint fcd_conversion_lines_unique unique (conversion_id, line_no),
  constraint fcd_conversion_lines_amount_chk check (
    native_amount > 0
    and carrying_thb_out >= 0
    and actual_thb_received >= 0
  )
);

create table if not exists public.fcd_status_logs (
  id bigint generated by default as identity primary key,
  event_key text not null unique,
  entity_type text not null,
  entity_id bigint not null,
  action text not null,
  from_status text,
  to_status text,
  note text,
  meta jsonb,
  created_at timestamptz not null default now(),
  created_by text
);

commit;
