create table public.customer_advance_statuses (
  id bigint generated by default as identity primary key,
  code text not null,
  name text not null,
  sort_order integer not null,
  is_initial boolean not null default false,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint customer_advance_statuses_code_key unique (code),
  constraint customer_advance_statuses_sort_order_key unique (sort_order),
  constraint customer_advance_statuses_code_check check (code = lower(code) and code ~ '^[a-z_]+$')
);

create unique index customer_advance_statuses_one_initial
  on public.customer_advance_statuses (is_initial)
  where is_initial;

insert into public.customer_advance_statuses (code, name, sort_order, is_initial) values
  ('pending_receipt', 'รอรับชำระ', 10, true),
  ('partially_received', 'รับชำระบางส่วน', 20, false),
  ('received', 'รับชำระครบ', 30, false),
  ('partially_allocated', 'ใช้หักบิลบางส่วน', 40, false),
  ('allocated', 'ใช้หักบิลครบ', 50, false),
  ('cancelled', 'ยกเลิก', 90, false);

create table public.customer_advances (
  id bigint generated by default as identity primary key,
  doc_no text not null,
  document_date date not null,
  customer_id bigint not null references public.customers(id) on delete restrict on update no action,
  customer_code_snapshot text not null,
  customer_name_snapshot text not null,
  invoice_no text,
  contract_no text,
  currency_code text not null references public.currencies(code) on delete restrict on update no action,
  target_amount numeric(18, 2) not null,
  received_amount numeric(18, 2) not null default 0,
  available_amount numeric(18, 2) not null default 0,
  allocated_amount numeric(18, 2) not null default 0,
  status_id bigint not null references public.customer_advance_statuses(id) on delete restrict on update no action,
  remark text,
  created_at timestamptz not null default now(),
  created_by text not null,
  updated_at timestamptz not null default now(),
  updated_by text not null,
  version integer not null default 1,
  cancelled_at timestamptz,
  cancelled_by text,
  cancel_reason text,
  constraint customer_advances_doc_no_key unique (doc_no),
  constraint customer_advances_amounts_check check (
    target_amount > 0
    and received_amount >= 0
    and available_amount >= 0
    and allocated_amount >= 0
    and received_amount <= target_amount
    and allocated_amount <= available_amount
  )
);

create table public.customer_advance_items (
  id bigint generated by default as identity primary key,
  customer_advance_id bigint not null references public.customer_advances(id) on delete restrict on update no action,
  line_no integer not null,
  product_id bigint not null references public.products(id) on delete restrict on update no action,
  product_code_snapshot text not null,
  product_name_snapshot text not null,
  quantity numeric(18, 2) not null,
  gross_weight numeric(18, 2) not null,
  net_weight numeric(18, 2) not null,
  created_at timestamptz not null default now(),
  created_by text not null,
  updated_at timestamptz not null default now(),
  updated_by text not null,
  constraint customer_advance_items_line_key unique (customer_advance_id, line_no),
  constraint customer_advance_items_values_check check (
    line_no > 0
    and quantity > 0
    and gross_weight >= 0
    and net_weight >= 0
    and net_weight <= gross_weight
  )
);

create table public.customer_advance_status_logs (
  id bigint generated by default as identity primary key,
  event_key text not null,
  customer_advance_id bigint not null references public.customer_advances(id) on delete restrict on update no action,
  customer_advance_doc_no text not null,
  from_status_id bigint references public.customer_advance_statuses(id) on delete restrict on update no action,
  to_status_id bigint not null references public.customer_advance_statuses(id) on delete restrict on update no action,
  action text not null,
  target_amount_snapshot numeric(18, 2) not null,
  received_amount_snapshot numeric(18, 2) not null,
  available_amount_snapshot numeric(18, 2) not null,
  allocated_amount_snapshot numeric(18, 2) not null,
  note text,
  meta jsonb,
  created_at timestamptz not null default now(),
  created_by text not null,
  constraint customer_advance_status_logs_event_key_key unique (event_key),
  constraint customer_advance_status_logs_action_check check (action = lower(action) and action ~ '^[a-z_]+$')
);

create index idx_customer_advances_document_date on public.customer_advances (document_date desc, doc_no desc);
create index idx_customer_advances_customer_date on public.customer_advances (customer_id, document_date desc, doc_no desc);
create index idx_customer_advances_status_date on public.customer_advances (status_id, document_date desc, doc_no desc);
create index idx_customer_advances_invoice_no on public.customer_advances (invoice_no) where invoice_no is not null;
create index idx_customer_advances_contract_no on public.customer_advances (contract_no) where contract_no is not null;
create index idx_customer_advance_items_advance_line on public.customer_advance_items (customer_advance_id, line_no);
create index idx_customer_advance_items_product on public.customer_advance_items (product_id);
create index idx_customer_advance_status_logs_advance_created on public.customer_advance_status_logs (customer_advance_id, created_at desc);
